import { NextResponse } from 'next/server';

export async function GET() {
  const siteUrl = (() => {
    try {
      return new URL(process.env.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000').origin;
    } catch {
      return 'http://localhost:3000';
    }
  })();

  const robotsTxt = `# Robots.txt generated by Next.js

User-agent: *
Disallow: /admin/
Disallow: /api/

Sitemap: ${siteUrl}/api/sitemap
`;

  return new NextResponse(robotsTxt, {
    headers: {
      'Content-Type': 'text/plain',
      'Cache-Control': 'public, max-age=86400, s-maxage=86400',
    },
  });
}
